seg fault on info

diff --git a/Rqpdf/configure.in b/Rqpdf/configure.in
--- a/Rqpdf/configure.in
+++ b/Rqpdf/configure.in
@@ -3,14 +3,14 @@ AC_INIT(src)
 AC_PATH_PROG(PKG_CONFIG, pkg-config)
 
 if test -z "$PKG_CONFIG" ; then
-echo "Cannot find pkg-config
-exit 1
+  echo "Cannot find pkg-config"
+  exit 1
 fi
 
 AC_SUBST(PKG_CONFIG)
 
-QPDF_VERSION=`$PKG_CONFIG --modversion libqpdf`
-
+QPDF_VERSION=`${PKG_CONFIG} --modversion libqpdf`
+echo "QPDF Version = $QPDF_VERSION"
 AC_SUBST(QPDF_VERSION)
 
 AC_OUTPUT(src/Makevars R/version.R)
